spring:
  application:
    name: vizo

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5431}/${DATABASE_NAME:vizo}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

api:
  security:
    jwt:
      secret: ${JWT_SECRET}

client:
  url: ${CLIENT_URL}

analyser:
  url: ${ANALYSER_URL}
